import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { StepProvider } from '@/src/components/step-context';

const geistUbuntuBold = localFont({
  src: './fonts/Ubuntu-Bold.ttf',
  variable: '--font-geist-bold',
  weight: '100 900',
});
const geistUbuntuMedium = localFont({
  src: './fonts/Ubuntu-Medium.ttf',
  variable: '--font-geist-med',
  weight: '100 900',
});
const geistUbuntuRegular = localFont({
  src: './fonts/Ubuntu-Regular.ttf',
  variable: '--font-geist-reg',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'MultiStep Forms',
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#eef5ff]  ${geistUbuntuBold.variable} ${geistUbuntuMedium.variable} ${geistUbuntuRegular.variable} `}
      >
        <StepProvider>{children}</StepProvider>
      </body>
    </html>
  );
}
